/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "main/gdm_wifi_base_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(chip_rpc_Empty, chip_rpc_Empty, AUTO)


PB_BIND(chip_rpc_Channel, chip_rpc_Channel, AUTO)


PB_BIND(chip_rpc_Ssid, chip_rpc_Ssid, AUTO)


PB_BIND(chip_rpc_State, chip_rpc_State, AUTO)


PB_BIND(chip_rpc_MacAddress, chip_rpc_MacAddress, AUTO)


PB_BIND(chip_rpc_WiFiInterface, chip_rpc_WiFiInterface, AUTO)


PB_BIND(chip_rpc_IP4Address, chip_rpc_IP4Address, AUTO)


PB_BIND(chip_rpc_IP6Address, chip_rpc_IP6Address, AUTO)


PB_BIND(chip_rpc_ScanConfig, chip_rpc_ScanConfig, AUTO)


PB_BIND(chip_rpc_ScanResult, chip_rpc_ScanResult, AUTO)


PB_BIND(chip_rpc_ScanResults, chip_rpc_ScanResults, 2)


PB_BIND(chip_rpc_ConnectionData, chip_rpc_ConnectionData, AUTO)


PB_BIND(chip_rpc_ConnectionResult, chip_rpc_ConnectionResult, AUTO)





