/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "main/ipv6_only_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(chip_rpc_PingTestConfig, chip_rpc_PingTestConfig, AUTO)


PB_BIND(chip_rpc_PingTestResponse, chip_rpc_PingTestResponse, 2)



